// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user/user.proto

package user_grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	date "google.golang.org/genproto/googleapis/type/date"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	ID                   string     `protobuf:"bytes,1,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	Email                string     `protobuf:"bytes,2,opt,name=Email,json=email,proto3" json:"Email,omitempty"`
	Password             string     `protobuf:"bytes,3,opt,name=Password,json=password,proto3" json:"Password,omitempty"`
	Role                 string     `protobuf:"bytes,4,opt,name=Role,json=role,proto3" json:"Role,omitempty"`
	CreatedAt            *date.Date `protobuf:"bytes,5,opt,name=created_at,proto3" json:"created_at,omitempty"`
	UpdatedAt            *date.Date `protobuf:"bytes,6,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	DeletedAt            *date.Date `protobuf:"bytes,7,opt,name=deleted_at,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *User) GetCreatedAt() *date.Date {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *date.Date {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *User) GetDeletedAt() *date.Date {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type CreateUserRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=Email,json=email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=Password,json=password,proto3" json:"Password,omitempty"`
	Role                 string   `protobuf:"bytes,4,opt,name=Role,json=role,proto3" json:"Role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{1}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type DeleteUserRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{2}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type UpdateUserRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=Email,json=email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=Password,json=password,proto3" json:"Password,omitempty"`
	Role                 string   `protobuf:"bytes,4,opt,name=Role,json=role,proto3" json:"Role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{3}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *UpdateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UpdateUserRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type EmptyUserResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyUserResponse) Reset()         { *m = EmptyUserResponse{} }
func (m *EmptyUserResponse) String() string { return proto.CompactTextString(m) }
func (*EmptyUserResponse) ProtoMessage()    {}
func (*EmptyUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{4}
}

func (m *EmptyUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyUserResponse.Unmarshal(m, b)
}
func (m *EmptyUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyUserResponse.Marshal(b, m, deterministic)
}
func (m *EmptyUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyUserResponse.Merge(m, src)
}
func (m *EmptyUserResponse) XXX_Size() int {
	return xxx_messageInfo_EmptyUserResponse.Size(m)
}
func (m *EmptyUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyUserResponse proto.InternalMessageInfo

type UserResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,json=code,proto3" json:"Code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,json=message,proto3" json:"Message,omitempty"`
	Result               []byte   `protobuf:"bytes,3,opt,name=Result,json=result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{5}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UserResponse) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*CreateUserRequest)(nil), "user.CreateUserRequest")
	proto.RegisterType((*DeleteUserRequest)(nil), "user.DeleteUserRequest")
	proto.RegisterType((*UpdateUserRequest)(nil), "user.UpdateUserRequest")
	proto.RegisterType((*EmptyUserResponse)(nil), "user.EmptyUserResponse")
	proto.RegisterType((*UserResponse)(nil), "user.UserResponse")
}

func init() {
	proto.RegisterFile("user/user.proto", fileDescriptor_ed89022014131a74)
}

var fileDescriptor_ed89022014131a74 = []byte{
	// 497 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0xe5, 0xd4, 0x71, 0xd2, 0x49, 0x45, 0xeb, 0xa5, 0x14, 0xcb, 0x70, 0xa8, 0x5c, 0x21,
	0x55, 0x3d, 0xd8, 0x6a, 0xb9, 0x95, 0x1b, 0x4d, 0x15, 0xf5, 0x50, 0x01, 0x2e, 0xbd, 0x70, 0x41,
	0xdb, 0xec, 0x28, 0x58, 0x72, 0xbc, 0x66, 0x77, 0x13, 0x94, 0x2b, 0xaf, 0xc0, 0xa3, 0xf1, 0x0a,
	0x9c, 0xb9, 0x71, 0x47, 0x3b, 0x6b, 0x37, 0x45, 0xa1, 0x55, 0x7b, 0xe8, 0x25, 0xf2, 0xec, 0xce,
	0xff, 0xcd, 0xbf, 0x33, 0xa3, 0xc0, 0xe6, 0x4c, 0xa3, 0xca, 0xec, 0x4f, 0x5a, 0x2b, 0x69, 0x24,
	0xf3, 0xed, 0x77, 0xfc, 0x72, 0x22, 0xe5, 0xa4, 0xc4, 0x8c, 0xd7, 0x45, 0xc6, 0xab, 0x4a, 0x1a,
	0x6e, 0x0a, 0x59, 0x69, 0x97, 0x13, 0xef, 0x34, 0xb7, 0x66, 0x51, 0x63, 0x26, 0xb8, 0x41, 0x77,
	0x9e, 0xfc, 0xf1, 0xc0, 0xbf, 0xd4, 0xa8, 0xd8, 0x13, 0xe8, 0x9c, 0x0d, 0x23, 0x6f, 0xd7, 0xdb,
	0x5f, 0xcf, 0x3b, 0x85, 0x60, 0xdb, 0xd0, 0x3d, 0x9d, 0xf2, 0xa2, 0x8c, 0x3a, 0x74, 0xd4, 0x45,
	0x1b, 0xb0, 0x18, 0xfa, 0xef, 0xb9, 0xd6, 0xdf, 0xa4, 0x12, 0xd1, 0x1a, 0x5d, 0xf4, 0xeb, 0x26,
	0x66, 0x0c, 0xfc, 0x5c, 0x96, 0x18, 0xf9, 0x74, 0xee, 0x2b, 0x59, 0x22, 0x3b, 0x04, 0x18, 0x2b,
	0xe4, 0x06, 0xc5, 0x67, 0x6e, 0xa2, 0xee, 0xae, 0xb7, 0x3f, 0x38, 0x0a, 0x53, 0xe7, 0x25, 0xb5,
	0x5e, 0xd2, 0x21, 0x37, 0x98, 0xdf, 0x48, 0xb2, 0x92, 0x59, 0x2d, 0x5a, 0x49, 0x70, 0xab, 0x64,
	0x99, 0x64, 0x25, 0x02, 0x4b, 0x6c, 0x24, 0xbd, 0x5b, 0x25, 0xcb, 0xa4, 0xa4, 0x80, 0xf0, 0x84,
	0x6a, 0xda, 0xc7, 0xe7, 0xf8, 0x75, 0x86, 0xda, 0x3c, 0x4e, 0x0f, 0x92, 0x3d, 0x08, 0x87, 0x54,
	0xf8, 0x8e, 0x52, 0xd6, 0xcf, 0x25, 0x3d, 0xe8, 0xf1, 0xfd, 0x3c, 0x85, 0xf0, 0x74, 0x5a, 0x9b,
	0x85, 0xab, 0xa4, 0x6b, 0x59, 0x69, 0x4c, 0x3e, 0xc2, 0xc6, 0xcd, 0xd8, 0x0a, 0x4f, 0xa4, 0x40,
	0x2a, 0xde, 0xcd, 0xfd, 0xb1, 0x14, 0xc8, 0x22, 0xe8, 0x9d, 0xa3, 0xd6, 0x7c, 0x82, 0x8d, 0x81,
	0xde, 0xd4, 0x85, 0x6c, 0x07, 0x82, 0x1c, 0xf5, 0xac, 0x34, 0x64, 0x60, 0x23, 0x0f, 0x14, 0x45,
	0x47, 0xbf, 0xd7, 0x60, 0x60, 0xb1, 0x17, 0xa8, 0xe6, 0xc5, 0x18, 0xd9, 0x07, 0x08, 0x5c, 0xd7,
	0xd9, 0xf3, 0x94, 0x16, 0x78, 0x65, 0x06, 0x31, 0x73, 0x17, 0xff, 0x98, 0x8b, 0xbf, 0xff, 0xfc,
	0xf5, 0xa3, 0xb3, 0x9d, 0x6c, 0x66, 0xf3, 0x43, 0x5a, 0xfc, 0xcc, 0xed, 0xcb, 0xb1, 0x77, 0x60,
	0x91, 0xae, 0xbb, 0x2d, 0x72, 0xa5, 0xd7, 0xf7, 0x44, 0xba, 0xe5, 0x68, 0x90, 0x6e, 0x16, 0x2d,
	0x72, 0x65, 0x32, 0x77, 0x21, 0xe3, 0x25, 0xd2, 0xad, 0xa8, 0x45, 0x8e, 0x20, 0x18, 0xa1, 0x79,
	0x57, 0x5d, 0x23, 0x57, 0x26, 0xf0, 0x5f, 0xe4, 0x16, 0x21, 0x81, 0xf5, 0x5b, 0x24, 0x3b, 0x83,
	0xde, 0x08, 0xcd, 0x39, 0xaf, 0x16, 0x0f, 0x23, 0x85, 0x44, 0x1a, 0xb0, 0xf5, 0x96, 0xa4, 0x59,
	0x0e, 0xc1, 0x05, 0x72, 0x35, 0xfe, 0xf2, 0x30, 0xd2, 0x0b, 0x22, 0x3d, 0x4b, 0xb6, 0xae, 0x49,
	0x99, 0x26, 0xcc, 0xb1, 0x77, 0xf0, 0xf6, 0xd5, 0xa7, 0x3d, 0x81, 0x65, 0x31, 0x47, 0xb5, 0xc8,
	0x8a, 0xca, 0xa0, 0xaa, 0x78, 0xe9, 0x7a, 0x41, 0x7f, 0x37, 0x6f, 0xec, 0x67, 0x7d, 0x75, 0x15,
	0x50, 0xf4, 0xfa, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x05, 0x8e, 0xe9, 0xea, 0xcb, 0x04, 0x00,
	0x00,
}
