// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: internal/iam/infra/grpc/user/user.proto

package grpc_user

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=UserName,json=username,proto3" json:"UserName,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=Email,json=email,proto3" json:"Email,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=Password,json=password,proto3" json:"Password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_internal_iam_infra_grpc_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_internal_iam_infra_grpc_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_internal_iam_infra_grpc_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *User) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=UserName,json=user_name,proto3" json:"UserName,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=Email,json=email,proto3" json:"Email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=Password,json=password,proto3" json:"Password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_internal_iam_infra_grpc_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_iam_infra_grpc_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_internal_iam_infra_grpc_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_internal_iam_infra_grpc_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_iam_infra_grpc_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_internal_iam_infra_grpc_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteUserRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_internal_iam_infra_grpc_user_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_iam_infra_grpc_user_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_internal_iam_infra_grpc_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UpdateUserRequest) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=Code,json=code,proto3" json:"Code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=Message,json=message,proto3" json:"Message,omitempty"`
	Result        []*structpb.Value      `protobuf:"bytes,3,rep,name=Result,json=result,proto3" json:"Result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_internal_iam_infra_grpc_user_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_internal_iam_infra_grpc_user_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_internal_iam_infra_grpc_user_user_proto_rawDescGZIP(), []int{4}
}

func (x *Response) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetResult() []*structpb.Value {
	if x != nil {
		return x.Result
	}
	return nil
}

type GETRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryParams   *structpb.Struct       `protobuf:"bytes,1,opt,name=query_params,json=queryParams,proto3" json:"query_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GETRequest) Reset() {
	*x = GETRequest{}
	mi := &file_internal_iam_infra_grpc_user_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GETRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GETRequest) ProtoMessage() {}

func (x *GETRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_iam_infra_grpc_user_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GETRequest.ProtoReflect.Descriptor instead.
func (*GETRequest) Descriptor() ([]byte, []int) {
	return file_internal_iam_infra_grpc_user_user_proto_rawDescGZIP(), []int{5}
}

func (x *GETRequest) GetQueryParams() *structpb.Struct {
	if x != nil {
		return x.QueryParams
	}
	return nil
}

var File_internal_iam_infra_grpc_user_user_proto protoreflect.FileDescriptor

const file_internal_iam_infra_grpc_user_user_proto_rawDesc = "" +
	"\n" +
	"'internal/iam/infra/grpc/user/user.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\"d\n" +
	"\x04User\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bUserName\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05Email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bPassword\x18\x04 \x01(\tR\bpassword\"b\n" +
	"\x11CreateUserRequest\x12\x1b\n" +
	"\bUserName\x18\x01 \x01(\tR\tuser_name\x12\x14\n" +
	"\x05Email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bPassword\x18\x03 \x01(\tR\bpassword\"#\n" +
	"\x11DeleteUserRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02id\"\x96\x01\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02id\x126\n" +
	"\x06fields\x18\x02 \x03(\v2\x1e.UpdateUserRequest.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"h\n" +
	"\bResponse\x12\x12\n" +
	"\x04Code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\aMessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\x06Result\x18\x03 \x03(\v2\x16.google.protobuf.ValueR\x06result\"H\n" +
	"\n" +
	"GETRequest\x12:\n" +
	"\fquery_params\x18\x01 \x01(\v2\x17.google.protobuf.StructR\vqueryParams2\xcf\x02\n" +
	"\vUserService\x12A\n" +
	"\x04Save\x12\x12.CreateUserRequest\x1a\t.Response\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/user/create\x12C\n" +
	"\x06Delete\x12\x12.DeleteUserRequest\x1a\t.Response\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/user/delete\x12C\n" +
	"\x06Update\x12\x12.UpdateUserRequest\x1a\t.Response\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\x1a\x0f/v1/user/update\x120\n" +
	"\x04Find\x12\v.GETRequest\x1a\t.Response\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/v1/user\x12A\n" +
	"\fListByTenant\x12\v.GETRequest\x1a\t.Response\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/users/tenanatB\vZ\tgrpc.userb\x06proto3"

var (
	file_internal_iam_infra_grpc_user_user_proto_rawDescOnce sync.Once
	file_internal_iam_infra_grpc_user_user_proto_rawDescData []byte
)

func file_internal_iam_infra_grpc_user_user_proto_rawDescGZIP() []byte {
	file_internal_iam_infra_grpc_user_user_proto_rawDescOnce.Do(func() {
		file_internal_iam_infra_grpc_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_iam_infra_grpc_user_user_proto_rawDesc), len(file_internal_iam_infra_grpc_user_user_proto_rawDesc)))
	})
	return file_internal_iam_infra_grpc_user_user_proto_rawDescData
}

var file_internal_iam_infra_grpc_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_iam_infra_grpc_user_user_proto_goTypes = []any{
	(*User)(nil),              // 0: User
	(*CreateUserRequest)(nil), // 1: CreateUserRequest
	(*DeleteUserRequest)(nil), // 2: DeleteUserRequest
	(*UpdateUserRequest)(nil), // 3: UpdateUserRequest
	(*Response)(nil),          // 4: Response
	(*GETRequest)(nil),        // 5: GETRequest
	nil,                       // 6: UpdateUserRequest.FieldsEntry
	(*structpb.Value)(nil),    // 7: google.protobuf.Value
	(*structpb.Struct)(nil),   // 8: google.protobuf.Struct
}
var file_internal_iam_infra_grpc_user_user_proto_depIdxs = []int32{
	6, // 0: UpdateUserRequest.fields:type_name -> UpdateUserRequest.FieldsEntry
	7, // 1: Response.Result:type_name -> google.protobuf.Value
	8, // 2: GETRequest.query_params:type_name -> google.protobuf.Struct
	1, // 3: UserService.Save:input_type -> CreateUserRequest
	2, // 4: UserService.Delete:input_type -> DeleteUserRequest
	3, // 5: UserService.Update:input_type -> UpdateUserRequest
	5, // 6: UserService.Find:input_type -> GETRequest
	5, // 7: UserService.ListByTenant:input_type -> GETRequest
	4, // 8: UserService.Save:output_type -> Response
	4, // 9: UserService.Delete:output_type -> Response
	4, // 10: UserService.Update:output_type -> Response
	4, // 11: UserService.Find:output_type -> Response
	4, // 12: UserService.ListByTenant:output_type -> Response
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_iam_infra_grpc_user_user_proto_init() }
func file_internal_iam_infra_grpc_user_user_proto_init() {
	if File_internal_iam_infra_grpc_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_iam_infra_grpc_user_user_proto_rawDesc), len(file_internal_iam_infra_grpc_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_iam_infra_grpc_user_user_proto_goTypes,
		DependencyIndexes: file_internal_iam_infra_grpc_user_user_proto_depIdxs,
		MessageInfos:      file_internal_iam_infra_grpc_user_user_proto_msgTypes,
	}.Build()
	File_internal_iam_infra_grpc_user_user_proto = out.File
	file_internal_iam_infra_grpc_user_user_proto_goTypes = nil
	file_internal_iam_infra_grpc_user_user_proto_depIdxs = nil
}
