// Code generated by protoc-gen-go. DO NOT EDIT.
// source: profile/profile.proto

package profile_grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	date "google.golang.org/genproto/googleapis/type/date"
	anypb "google.golang.org/protobuf/types/known/anypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Profile struct {
	ID                   string     `protobuf:"bytes,1,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	UserID               string     `protobuf:"bytes,2,opt,name=UserID,json=user_id,proto3" json:"UserID,omitempty"`
	FullName             string     `protobuf:"bytes,3,opt,name=FullName,json=full_name,proto3" json:"FullName,omitempty"`
	Avatar               string     `protobuf:"bytes,4,opt,name=Avatar,json=avatar,proto3" json:"Avatar,omitempty"`
	Bio                  string     `protobuf:"bytes,5,opt,name=Bio,json=bio,proto3" json:"Bio,omitempty"`
	CreatedAt            *date.Date `protobuf:"bytes,6,opt,name=created_at,proto3" json:"created_at,omitempty"`
	UpdatedAt            *date.Date `protobuf:"bytes,7,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	DeletedAt            *date.Date `protobuf:"bytes,8,opt,name=deleted_at,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b6f1294962b1d54, []int{0}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Profile) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Profile) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *Profile) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *Profile) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *Profile) GetCreatedAt() *date.Date {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Profile) GetUpdatedAt() *date.Date {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Profile) GetDeletedAt() *date.Date {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type CreateProfileRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=UserID,json=user_id,proto3" json:"UserID,omitempty"`
	FullName             string   `protobuf:"bytes,3,opt,name=FullName,json=full_name,proto3" json:"FullName,omitempty"`
	Avatar               string   `protobuf:"bytes,4,opt,name=Avatar,json=avatar,proto3" json:"Avatar,omitempty"`
	Bio                  string   `protobuf:"bytes,5,opt,name=Bio,json=bio,proto3" json:"Bio,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProfileRequest) Reset()         { *m = CreateProfileRequest{} }
func (m *CreateProfileRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProfileRequest) ProtoMessage()    {}
func (*CreateProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b6f1294962b1d54, []int{1}
}

func (m *CreateProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProfileRequest.Unmarshal(m, b)
}
func (m *CreateProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProfileRequest.Marshal(b, m, deterministic)
}
func (m *CreateProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProfileRequest.Merge(m, src)
}
func (m *CreateProfileRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProfileRequest.Size(m)
}
func (m *CreateProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProfileRequest proto.InternalMessageInfo

func (m *CreateProfileRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *CreateProfileRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *CreateProfileRequest) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *CreateProfileRequest) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *CreateProfileRequest) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

type DeleteProfileRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteProfileRequest) Reset()         { *m = DeleteProfileRequest{} }
func (m *DeleteProfileRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteProfileRequest) ProtoMessage()    {}
func (*DeleteProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b6f1294962b1d54, []int{2}
}

func (m *DeleteProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteProfileRequest.Unmarshal(m, b)
}
func (m *DeleteProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteProfileRequest.Marshal(b, m, deterministic)
}
func (m *DeleteProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteProfileRequest.Merge(m, src)
}
func (m *DeleteProfileRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteProfileRequest.Size(m)
}
func (m *DeleteProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteProfileRequest proto.InternalMessageInfo

func (m *DeleteProfileRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type UpdateProfileRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=UserID,json=user_id,proto3" json:"UserID,omitempty"`
	FullName             string   `protobuf:"bytes,3,opt,name=FullName,json=full_name,proto3" json:"FullName,omitempty"`
	Avatar               string   `protobuf:"bytes,4,opt,name=Avatar,json=avatar,proto3" json:"Avatar,omitempty"`
	Bio                  string   `protobuf:"bytes,5,opt,name=Bio,json=bio,proto3" json:"Bio,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProfileRequest) Reset()         { *m = UpdateProfileRequest{} }
func (m *UpdateProfileRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateProfileRequest) ProtoMessage()    {}
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b6f1294962b1d54, []int{3}
}

func (m *UpdateProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProfileRequest.Unmarshal(m, b)
}
func (m *UpdateProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProfileRequest.Marshal(b, m, deterministic)
}
func (m *UpdateProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProfileRequest.Merge(m, src)
}
func (m *UpdateProfileRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateProfileRequest.Size(m)
}
func (m *UpdateProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProfileRequest proto.InternalMessageInfo

func (m *UpdateProfileRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *UpdateProfileRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UpdateProfileRequest) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *UpdateProfileRequest) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UpdateProfileRequest) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

type EmptyProfileResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyProfileResponse) Reset()         { *m = EmptyProfileResponse{} }
func (m *EmptyProfileResponse) String() string { return proto.CompactTextString(m) }
func (*EmptyProfileResponse) ProtoMessage()    {}
func (*EmptyProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b6f1294962b1d54, []int{4}
}

func (m *EmptyProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyProfileResponse.Unmarshal(m, b)
}
func (m *EmptyProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyProfileResponse.Marshal(b, m, deterministic)
}
func (m *EmptyProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyProfileResponse.Merge(m, src)
}
func (m *EmptyProfileResponse) XXX_Size() int {
	return xxx_messageInfo_EmptyProfileResponse.Size(m)
}
func (m *EmptyProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyProfileResponse proto.InternalMessageInfo

type ProfileResponse struct {
	Code                 int32      `protobuf:"varint,1,opt,name=Code,json=code,proto3" json:"Code,omitempty"`
	Message              string     `protobuf:"bytes,2,opt,name=Message,json=message,proto3" json:"Message,omitempty"`
	Result               *anypb.Any `protobuf:"bytes,3,opt,name=Result,json=result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProfileResponse) Reset()         { *m = ProfileResponse{} }
func (m *ProfileResponse) String() string { return proto.CompactTextString(m) }
func (*ProfileResponse) ProtoMessage()    {}
func (*ProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b6f1294962b1d54, []int{5}
}

func (m *ProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileResponse.Unmarshal(m, b)
}
func (m *ProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileResponse.Marshal(b, m, deterministic)
}
func (m *ProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileResponse.Merge(m, src)
}
func (m *ProfileResponse) XXX_Size() int {
	return xxx_messageInfo_ProfileResponse.Size(m)
}
func (m *ProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileResponse proto.InternalMessageInfo

func (m *ProfileResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ProfileResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ProfileResponse) GetResult() *anypb.Any {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*Profile)(nil), "Profile")
	proto.RegisterType((*CreateProfileRequest)(nil), "CreateProfileRequest")
	proto.RegisterType((*DeleteProfileRequest)(nil), "DeleteProfileRequest")
	proto.RegisterType((*UpdateProfileRequest)(nil), "UpdateProfileRequest")
	proto.RegisterType((*EmptyProfileResponse)(nil), "EmptyProfileResponse")
	proto.RegisterType((*ProfileResponse)(nil), "ProfileResponse")
}

func init() {
	proto.RegisterFile("profile/profile.proto", fileDescriptor_8b6f1294962b1d54)
}

var fileDescriptor_8b6f1294962b1d54 = []byte{
	// 522 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x94, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xe5, 0xa4, 0xdd, 0xb4, 0x93, 0x12, 0xca, 0xd6, 0x69, 0xad, 0xf0, 0x47, 0x95, 0x0f,
	0xa8, 0xaa, 0x90, 0xad, 0x86, 0x5b, 0x6f, 0x6d, 0x43, 0x4b, 0x0f, 0x85, 0xe2, 0xaa, 0x17, 0x2e,
	0xd1, 0x26, 0x9e, 0x04, 0x4b, 0xb6, 0xd7, 0xec, 0xae, 0x23, 0xf9, 0xca, 0x81, 0x07, 0x80, 0x47,
	0xe3, 0x15, 0xb8, 0xf1, 0x12, 0xc8, 0x6b, 0x9b, 0xba, 0x95, 0x83, 0x72, 0x82, 0x53, 0xb4, 0x33,
	0xf3, 0xfd, 0xf6, 0xcb, 0x7e, 0x93, 0x40, 0x3f, 0x11, 0x7c, 0x16, 0x84, 0xe8, 0x96, 0x9f, 0x4e,
	0x22, 0xb8, 0xe2, 0x03, 0x73, 0xce, 0xf9, 0x3c, 0x44, 0x97, 0x25, 0x81, 0xcb, 0xe2, 0xac, 0xac,
	0x3e, 0xbb, 0x57, 0x8d, 0xb9, 0x62, 0x2a, 0xe0, 0xb1, 0x2c, 0xbb, 0xfd, 0x5a, 0xd7, 0x67, 0xaa,
	0x44, 0xd9, 0xdf, 0x5a, 0xd0, 0xb9, 0x2e, 0xe0, 0xb4, 0x07, 0xad, 0xcb, 0x91, 0x65, 0xec, 0x1b,
	0x07, 0x9b, 0x5e, 0x2b, 0xf0, 0xe9, 0x1e, 0x90, 0x5b, 0x89, 0xe2, 0x72, 0x64, 0xb5, 0x74, 0xad,
	0x93, 0x4a, 0x14, 0xe3, 0xc0, 0xa7, 0x4f, 0x61, 0xe3, 0x3c, 0x0d, 0xc3, 0x77, 0x2c, 0x42, 0xab,
	0xad, 0x5b, 0x9b, 0xb3, 0x34, 0x0c, 0xc7, 0x31, 0x8b, 0x90, 0xee, 0x02, 0x39, 0x59, 0x30, 0xc5,
	0x84, 0xb5, 0xa6, 0x5b, 0x84, 0xe9, 0x13, 0xdd, 0x86, 0xf6, 0x69, 0xc0, 0xad, 0x75, 0x5d, 0x6c,
	0x4f, 0x02, 0x4e, 0x8f, 0x00, 0xa6, 0x02, 0x99, 0x42, 0x7f, 0xcc, 0x94, 0x45, 0xf6, 0x8d, 0x83,
	0xee, 0xf0, 0x89, 0x53, 0xf8, 0x74, 0x54, 0x96, 0xa0, 0x33, 0x62, 0x0a, 0xbd, 0xda, 0x50, 0x2e,
	0x49, 0x13, 0xbf, 0x92, 0x74, 0x96, 0x4a, 0xee, 0x86, 0x72, 0x89, 0x8f, 0x21, 0x96, 0x92, 0x8d,
	0xa5, 0x92, 0xbb, 0x21, 0xfb, 0xab, 0x01, 0xe6, 0x99, 0xbe, 0xb4, 0x7c, 0x1a, 0x0f, 0x3f, 0xa7,
	0x28, 0xd5, 0xbf, 0x7e, 0x21, 0xfb, 0x25, 0x98, 0x23, 0x6d, 0xeb, 0xef, 0x3e, 0xb4, 0xe1, 0x5b,
	0xfd, 0x95, 0xff, 0xb3, 0xe1, 0x5d, 0x30, 0xdf, 0x44, 0x89, 0xca, 0xfe, 0xd8, 0x90, 0x09, 0x8f,
	0x25, 0xda, 0x11, 0x3c, 0x7e, 0x50, 0xa2, 0x14, 0xd6, 0xce, 0xb8, 0x8f, 0xda, 0xdc, 0xba, 0xb7,
	0x36, 0xe5, 0x3e, 0x52, 0x0b, 0x3a, 0x57, 0x28, 0x25, 0x9b, 0x63, 0xe5, 0x2f, 0x2a, 0x8e, 0xf4,
	0x15, 0x10, 0x0f, 0x65, 0x1a, 0x2a, 0xed, 0xae, 0x3b, 0x34, 0xab, 0x04, 0xf5, 0x1a, 0x4f, 0xd2,
	0x99, 0x73, 0x12, 0x67, 0x1e, 0x11, 0x7a, 0x66, 0xf8, 0xab, 0x0d, 0xbd, 0xf2, 0xbe, 0x1b, 0x14,
	0x8b, 0x60, 0x8a, 0xf4, 0x1a, 0x48, 0x11, 0x29, 0xed, 0x3b, 0x4d, 0xd9, 0x0e, 0xb6, 0x9d, 0x87,
	0xa6, 0x9f, 0x7f, 0xf9, 0xf1, 0xf3, 0x7b, 0x6b, 0xcf, 0xa6, 0xee, 0xe2, 0xa8, 0xfa, 0x05, 0xba,
	0xc5, 0x32, 0x1e, 0x1b, 0x87, 0x39, 0xb1, 0x08, 0x87, 0xf6, 0x9d, 0xa6, 0x94, 0x56, 0x25, 0x16,
	0x8b, 0x57, 0x12, 0x8b, 0x14, 0x69, 0xdf, 0x69, 0x8a, 0x73, 0x39, 0x71, 0x70, 0x8f, 0x58, 0x6c,
	0x7f, 0x4e, 0x3c, 0x07, 0x72, 0x81, 0xea, 0x7d, 0x9c, 0x13, 0x9b, 0x82, 0x69, 0x20, 0xee, 0x68,
	0xe2, 0x23, 0xda, 0xad, 0x11, 0xe9, 0x5b, 0xe8, 0x5c, 0xa0, 0xba, 0x62, 0x71, 0xb6, 0x3a, 0xc8,
	0xd4, 0xa0, 0x1e, 0xdd, 0xaa, 0x81, 0x24, 0xfd, 0x00, 0xe4, 0x06, 0x99, 0x98, 0x7e, 0x5a, 0x1d,
	0xf4, 0x42, 0x83, 0x2c, 0x7b, 0xa7, 0x0e, 0x72, 0xa5, 0xa6, 0x1c, 0x1b, 0x87, 0xa7, 0xbd, 0x8f,
	0x5b, 0xd5, 0xff, 0xe3, 0x5c, 0x24, 0xd3, 0x09, 0xd1, 0x3b, 0xf1, 0xfa, 0x77, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xe1, 0xda, 0x9d, 0xd1, 0x3e, 0x05, 0x00, 0x00,
}
