// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth/auth.proto

package grpc_auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	anypb "google.golang.org/protobuf/types/known/anypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=UserName,json=user_name,proto3" json:"UserName,omitempty"`
	FullName             string   `protobuf:"bytes,2,opt,name=FullName,json=full_name,proto3" json:"FullName,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=Address,json=address,proto3" json:"Address,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=Email,json=email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=Password,json=password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{0}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *RegisterRequest) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *RegisterRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=Login,json=login,proto3" json:"Login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,json=password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{1}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type TwoFactoryConfirmRequest struct {
	Pin                  int32    `protobuf:"varint,1,opt,name=Pin,json=pin,proto3" json:"Pin,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=Email,json=email,proto3" json:"Email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TwoFactoryConfirmRequest) Reset()         { *m = TwoFactoryConfirmRequest{} }
func (m *TwoFactoryConfirmRequest) String() string { return proto.CompactTextString(m) }
func (*TwoFactoryConfirmRequest) ProtoMessage()    {}
func (*TwoFactoryConfirmRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{2}
}

func (m *TwoFactoryConfirmRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TwoFactoryConfirmRequest.Unmarshal(m, b)
}
func (m *TwoFactoryConfirmRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TwoFactoryConfirmRequest.Marshal(b, m, deterministic)
}
func (m *TwoFactoryConfirmRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TwoFactoryConfirmRequest.Merge(m, src)
}
func (m *TwoFactoryConfirmRequest) XXX_Size() int {
	return xxx_messageInfo_TwoFactoryConfirmRequest.Size(m)
}
func (m *TwoFactoryConfirmRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TwoFactoryConfirmRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TwoFactoryConfirmRequest proto.InternalMessageInfo

func (m *TwoFactoryConfirmRequest) GetPin() int32 {
	if m != nil {
		return m.Pin
	}
	return 0
}

func (m *TwoFactoryConfirmRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ResetPasswordRequest struct {
	Password             string   `protobuf:"bytes,1,opt,name=Password,json=passoword,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordRequest) Reset()         { *m = ResetPasswordRequest{} }
func (m *ResetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordRequest) ProtoMessage()    {}
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{3}
}

func (m *ResetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordRequest.Unmarshal(m, b)
}
func (m *ResetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ResetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordRequest.Merge(m, src)
}
func (m *ResetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordRequest.Size(m)
}
func (m *ResetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordRequest proto.InternalMessageInfo

func (m *ResetPasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ForgetPasswordRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,json=email,proto3" json:"Email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgetPasswordRequest) Reset()         { *m = ForgetPasswordRequest{} }
func (m *ForgetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ForgetPasswordRequest) ProtoMessage()    {}
func (*ForgetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{4}
}

func (m *ForgetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgetPasswordRequest.Unmarshal(m, b)
}
func (m *ForgetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgetPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ForgetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgetPasswordRequest.Merge(m, src)
}
func (m *ForgetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ForgetPasswordRequest.Size(m)
}
func (m *ForgetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForgetPasswordRequest proto.InternalMessageInfo

func (m *ForgetPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type LogoutRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,json=token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{5}
}

func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (m *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(m, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

func (m *LogoutRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{6}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type AuthResponse struct {
	Code                 int32      `protobuf:"varint,1,opt,name=Code,json=code,proto3" json:"Code,omitempty"`
	Message              string     `protobuf:"bytes,2,opt,name=Message,json=message,proto3" json:"Message,omitempty"`
	Data                 *anypb.Any `protobuf:"bytes,3,opt,name=Data,json=data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_712ec48c1eaf43a2, []int{7}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AuthResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AuthResponse) GetData() *anypb.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "RegisterRequest")
	proto.RegisterType((*LoginRequest)(nil), "LoginRequest")
	proto.RegisterType((*TwoFactoryConfirmRequest)(nil), "TwoFactoryConfirmRequest")
	proto.RegisterType((*ResetPasswordRequest)(nil), "ResetPasswordRequest")
	proto.RegisterType((*ForgetPasswordRequest)(nil), "ForgetPasswordRequest")
	proto.RegisterType((*LogoutRequest)(nil), "LogoutRequest")
	proto.RegisterType((*Empty)(nil), "Empty")
	proto.RegisterType((*AuthResponse)(nil), "AuthResponse")
}

func init() {
	proto.RegisterFile("auth/auth.proto", fileDescriptor_712ec48c1eaf43a2)
}

var fileDescriptor_712ec48c1eaf43a2 = []byte{
	// 437 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0xe5, 0xc4, 0x26, 0xc9, 0xa4, 0x51, 0x91, 0x09, 0x92, 0x09, 0x1c, 0x90, 0x25, 0xa4,
	0x0a, 0x09, 0x1b, 0xb5, 0xb7, 0x9e, 0x48, 0x0b, 0x91, 0x90, 0x0a, 0xaa, 0x4c, 0xb9, 0x70, 0x41,
	0xd3, 0x78, 0xe2, 0x5a, 0xd8, 0x3b, 0x66, 0x77, 0xdd, 0xca, 0x57, 0x5e, 0x81, 0x03, 0x0f, 0xc6,
	0x2b, 0xf0, 0x20, 0x68, 0xd7, 0x76, 0x30, 0x70, 0x89, 0xf4, 0xe7, 0xf3, 0xce, 0xff, 0xef, 0xfe,
	0x03, 0x87, 0x58, 0xeb, 0x9b, 0xd8, 0xfc, 0x44, 0x95, 0x64, 0xcd, 0xab, 0x47, 0x19, 0x73, 0x56,
	0x50, 0x6c, 0xd5, 0x75, 0xbd, 0x8b, 0x51, 0x34, 0x1d, 0x7a, 0xd2, 0x21, 0xac, 0xf2, 0x18, 0x85,
	0x60, 0x8d, 0x3a, 0x67, 0xa1, 0x5a, 0x1a, 0xfe, 0x70, 0xe0, 0x30, 0xa1, 0x2c, 0x57, 0x9a, 0x64,
	0x42, 0x5f, 0x6b, 0x52, 0xda, 0x7f, 0x0c, 0xd3, 0x8f, 0x8a, 0xe4, 0x7b, 0x2c, 0x29, 0x70, 0x9e,
	0x3a, 0x47, 0xb3, 0x64, 0x56, 0x2b, 0x92, 0x9f, 0x05, 0x96, 0x64, 0xe0, 0xa6, 0x2e, 0x0a, 0x0b,
	0x47, 0x2d, 0xdc, 0xd5, 0x45, 0xd1, 0xc2, 0x00, 0x26, 0xeb, 0x34, 0x95, 0xa4, 0x54, 0x30, 0xb6,
	0x6c, 0x82, 0xad, 0xf4, 0x97, 0xe0, 0xbd, 0x29, 0x31, 0x2f, 0x02, 0xd7, 0xfe, 0xef, 0x91, 0x11,
	0xfe, 0x0a, 0xa6, 0x97, 0xa8, 0xd4, 0x1d, 0xcb, 0x34, 0xf0, 0x2c, 0x98, 0x56, 0x9d, 0x0e, 0x5f,
	0xc1, 0xc1, 0x05, 0x67, 0xb9, 0xe8, 0x53, 0x2d, 0xc1, 0xb3, 0xba, 0x8b, 0xe4, 0x15, 0x46, 0xfc,
	0x35, 0x61, 0xf4, 0xcf, 0x84, 0x33, 0x08, 0xae, 0xee, 0x78, 0x83, 0x5b, 0xcd, 0xb2, 0x39, 0x67,
	0xb1, 0xcb, 0x65, 0xd9, 0x4f, 0xbb, 0x0f, 0xe3, 0xcb, 0x6e, 0x96, 0x97, 0x8c, 0xab, 0x5c, 0xfc,
	0x49, 0x38, 0x1a, 0x24, 0x0c, 0x4f, 0x60, 0x99, 0x90, 0x22, 0xdd, 0x9b, 0x0c, 0xde, 0x68, 0xef,
	0xdb, 0xbd, 0x91, 0xf1, 0x65, 0x6b, 0xfc, 0x02, 0x1e, 0x6e, 0x58, 0x66, 0xff, 0x9f, 0xda, 0x7b,
	0x38, 0x43, 0x8f, 0x67, 0xb0, 0xb8, 0xe0, 0x8c, 0x6b, 0x3d, 0xf8, 0xec, 0x8a, 0xbf, 0xd0, 0xfe,
	0xaa, 0xda, 0x88, 0x70, 0x62, 0x0e, 0x57, 0xba, 0x09, 0x77, 0x70, 0xb0, 0xae, 0xf5, 0x4d, 0x42,
	0xaa, 0x62, 0xa1, 0xc8, 0xf7, 0xc1, 0x3d, 0xe7, 0x94, 0xba, 0xcb, 0xb8, 0x5b, 0x4e, 0x6d, 0x13,
	0xef, 0x48, 0x29, 0xcc, 0xfa, 0x96, 0x26, 0x65, 0x2b, 0xfd, 0x23, 0x70, 0x5f, 0xa3, 0x46, 0x5b,
	0xd0, 0xfc, 0x78, 0x19, 0xb5, 0xeb, 0x11, 0xf5, 0x9b, 0x13, 0xad, 0x45, 0x93, 0xb8, 0x29, 0x6a,
	0x3c, 0x7e, 0x0b, 0x73, 0xe3, 0xf3, 0x81, 0xe4, 0x6d, 0xbe, 0x25, 0xff, 0xb4, 0x2b, 0xc0, 0x5f,
	0x44, 0xc3, 0x62, 0x56, 0x8b, 0x68, 0x98, 0x26, 0x7c, 0xf0, 0xed, 0xe7, 0xaf, 0xef, 0xa3, 0x45,
	0x38, 0x8d, 0x6f, 0x5f, 0xda, 0x15, 0x3d, 0x75, 0x9e, 0x9f, 0xcd, 0x3f, 0xcd, 0x32, 0x59, 0x6d,
	0x23, 0xa3, 0xaf, 0xef, 0x59, 0xaf, 0x93, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x75, 0x32, 0xc5,
	0xdc, 0xc6, 0x02, 0x00, 0x00,
}
