// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user/user.proto

package user_grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,proto3" json:"user_name,omitempty"`
	FullName             string   `protobuf:"bytes,3,opt,name=full_name,proto3" json:"full_name,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Password             string   `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	UserType             string   `protobuf:"bytes,7,opt,name=user_type,proto3" json:"user_type,omitempty"`
	Status               string   `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt            string   `protobuf:"bytes,9,opt,name=created_at,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,10,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	DeletedAt            string   `protobuf:"bytes,11,opt,name=deleted_at,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *User) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetUserType() string {
	if m != nil {
		return m.UserType
	}
	return ""
}

func (m *User) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *User) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *User) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *User) GetDeletedAt() string {
	if m != nil {
		return m.DeletedAt
	}
	return ""
}

type CreateUserRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=UserName,json=user_name,proto3" json:"UserName,omitempty"`
	FullName             string   `protobuf:"bytes,2,opt,name=FullName,json=full_name,proto3" json:"FullName,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=Address,json=address,proto3" json:"Address,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=Email,json=email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=Password,json=password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{1}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *CreateUserRequest) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *CreateUserRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type DeleteUserRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=Login,json=login,proto3" json:"Login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,json=password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{2}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *DeleteUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UpdateUserRequest struct {
	Pin                  int32    `protobuf:"varint,1,opt,name=Pin,json=pin,proto3" json:"Pin,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=Email,json=email,proto3" json:"Email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{3}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetPin() int32 {
	if m != nil {
		return m.Pin
	}
	return 0
}

func (m *UpdateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type EmptyUserResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyUserResponse) Reset()         { *m = EmptyUserResponse{} }
func (m *EmptyUserResponse) String() string { return proto.CompactTextString(m) }
func (*EmptyUserResponse) ProtoMessage()    {}
func (*EmptyUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{4}
}

func (m *EmptyUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyUserResponse.Unmarshal(m, b)
}
func (m *EmptyUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyUserResponse.Marshal(b, m, deterministic)
}
func (m *EmptyUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyUserResponse.Merge(m, src)
}
func (m *EmptyUserResponse) XXX_Size() int {
	return xxx_messageInfo_EmptyUserResponse.Size(m)
}
func (m *EmptyUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyUserResponse proto.InternalMessageInfo

type UserResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,json=code,proto3" json:"Code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,json=message,proto3" json:"Message,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=Data,json=data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{5}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UserResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*CreateUserRequest)(nil), "CreateUserRequest")
	proto.RegisterType((*DeleteUserRequest)(nil), "DeleteUserRequest")
	proto.RegisterType((*UpdateUserRequest)(nil), "UpdateUserRequest")
	proto.RegisterType((*EmptyUserResponse)(nil), "EmptyUserResponse")
	proto.RegisterType((*UserResponse)(nil), "UserResponse")
}

func init() {
	proto.RegisterFile("user/user.proto", fileDescriptor_ed89022014131a74)
}

var fileDescriptor_ed89022014131a74 = []byte{
	// 555 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xc1, 0x6e, 0xd3, 0x4c,
	0x10, 0xc7, 0x65, 0x27, 0x76, 0x9c, 0xc9, 0xf7, 0xd1, 0x66, 0x09, 0xc8, 0x72, 0x2a, 0x84, 0x7c,
	0x42, 0x3d, 0xd8, 0x02, 0x6e, 0x45, 0x08, 0x41, 0x1b, 0xc2, 0x81, 0x96, 0x28, 0x55, 0x2f, 0x5c,
	0xaa, 0x25, 0x3b, 0x04, 0x4b, 0x8e, 0xd7, 0x78, 0xd7, 0x45, 0xb9, 0xf2, 0x0a, 0x9c, 0x78, 0x0d,
	0xc4, 0x9b, 0xf0, 0x0a, 0x3c, 0x08, 0xda, 0x5d, 0x3b, 0x76, 0x12, 0x21, 0x7a, 0x89, 0x34, 0xf3,
	0xcf, 0xfc, 0x34, 0xfa, 0xed, 0xae, 0xe1, 0xa0, 0x14, 0x58, 0xc4, 0xea, 0x27, 0xca, 0x0b, 0x2e,
	0x79, 0x70, 0xb4, 0xe4, 0x7c, 0x99, 0x62, 0x4c, 0xf3, 0x24, 0xa6, 0x59, 0xc6, 0x25, 0x95, 0x09,
	0xcf, 0x84, 0x49, 0xc3, 0x9f, 0x36, 0x74, 0xaf, 0x04, 0x16, 0xe4, 0x0e, 0xd8, 0x09, 0xf3, 0xad,
	0x87, 0xd6, 0xa3, 0xfe, 0xdc, 0x4e, 0x18, 0x39, 0x82, 0xbe, 0x82, 0x5c, 0x67, 0x74, 0x85, 0xbe,
	0xad, 0xdb, 0x4d, 0x43, 0xa5, 0x1f, 0xcb, 0x34, 0x35, 0x69, 0xc7, 0xa4, 0x9b, 0x06, 0x19, 0x81,
	0x83, 0x2b, 0x9a, 0xa4, 0x7e, 0x57, 0x27, 0xa6, 0x20, 0x3e, 0xf4, 0x28, 0x63, 0x05, 0x0a, 0xe1,
	0x3b, 0xba, 0x5f, 0x97, 0x24, 0x00, 0x2f, 0xa7, 0x42, 0x7c, 0xe1, 0x05, 0xf3, 0x5d, 0x1d, 0x6d,
	0xea, 0xcd, 0x1e, 0x72, 0x9d, 0xa3, 0xdf, 0x6b, 0xed, 0xa1, 0x1a, 0xe4, 0x3e, 0xb8, 0x42, 0x52,
	0x59, 0x0a, 0xdf, 0xd3, 0x51, 0x55, 0x91, 0x07, 0x00, 0x8b, 0x02, 0xa9, 0x44, 0x76, 0x4d, 0xa5,
	0xdf, 0xd7, 0x59, 0xab, 0xa3, 0xf2, 0x32, 0x67, 0x75, 0x0e, 0x26, 0x6f, 0x3a, 0x2a, 0x67, 0x98,
	0x62, 0x95, 0x0f, 0x4c, 0xde, 0x74, 0xc2, 0xef, 0x16, 0x0c, 0x4f, 0x35, 0x4e, 0xc9, 0x9b, 0xe3,
	0xe7, 0x12, 0x85, 0x24, 0x63, 0xf0, 0x54, 0x79, 0xa1, 0xa4, 0x58, 0xbb, 0xca, 0xc6, 0xe0, 0xbd,
	0x2e, 0xd3, 0xf4, 0xa2, 0xe5, 0xb3, 0x31, 0xe6, 0x43, 0xef, 0x65, 0xe5, 0xa6, 0xb3, 0xed, 0x66,
	0x04, 0xce, 0x64, 0xdf, 0x65, 0x00, 0xde, 0xac, 0x36, 0xe6, 0x6c, 0x1b, 0x0b, 0x27, 0x30, 0x3c,
	0xd3, 0x9b, 0xb6, 0x57, 0x1b, 0x81, 0xf3, 0x96, 0x2f, 0x93, 0xac, 0xda, 0xcb, 0x49, 0x55, 0xb1,
	0x85, 0xb1, 0x77, 0x30, 0xcf, 0x60, 0x78, 0xa5, 0x85, 0xb4, 0x31, 0x87, 0xd0, 0x99, 0x55, 0x10,
	0x67, 0xde, 0xc9, 0x93, 0xac, 0xd9, 0xcf, 0x6e, 0xed, 0x17, 0xde, 0x85, 0xe1, 0x64, 0x95, 0xcb,
	0xb5, 0x99, 0x15, 0x39, 0xcf, 0x04, 0x86, 0x33, 0xf8, 0xaf, 0x5d, 0x13, 0x02, 0xdd, 0x53, 0xce,
	0xb0, 0xa2, 0x75, 0x17, 0x9c, 0x69, 0x11, 0xe7, 0x28, 0x04, 0x5d, 0xd6, 0x92, 0x7a, 0x2b, 0x53,
	0xaa, 0x7f, 0x9f, 0x51, 0x49, 0x2b, 0x3f, 0x5d, 0x46, 0x25, 0x7d, 0xf2, 0xa3, 0x03, 0x03, 0x85,
	0xbc, 0xc4, 0xe2, 0x26, 0x59, 0x20, 0x99, 0x82, 0x6b, 0x4e, 0x85, 0x90, 0x68, 0xef, 0x78, 0x82,
	0xff, 0xa3, 0xad, 0x75, 0x82, 0xaf, 0xbf, 0x7e, 0x7f, 0xb3, 0x47, 0xe1, 0x41, 0x7c, 0xf3, 0x58,
	0x3f, 0x98, 0xd8, 0x5c, 0x90, 0x13, 0xeb, 0x58, 0x81, 0x8c, 0x43, 0x42, 0xa2, 0x3d, 0x99, 0xff,
	0x06, 0x99, 0x9b, 0x52, 0x81, 0x8c, 0x45, 0x42, 0xa2, 0x3d, 0x9d, 0x7f, 0x01, 0x05, 0x0d, 0xc8,
	0x5c, 0x49, 0x05, 0x7a, 0x0e, 0xee, 0x14, 0xe5, 0xbb, 0x4c, 0x81, 0xf6, 0xd4, 0xee, 0x82, 0x0e,
	0x35, 0x08, 0x88, 0x57, 0x83, 0xc8, 0x0b, 0xe8, 0x4d, 0x51, 0x9e, 0xd3, 0x6c, 0x7d, 0x9b, 0xf9,
	0xa1, 0x9e, 0x1f, 0x90, 0x7e, 0x3d, 0x2f, 0xc8, 0x1b, 0x70, 0x2f, 0x91, 0x16, 0x8b, 0x4f, 0xb7,
	0x99, 0x1f, 0xeb, 0xf9, 0x7b, 0xe1, 0xe1, 0x66, 0x3e, 0x16, 0x7a, 0xf8, 0xc4, 0x3a, 0x7e, 0x35,
	0x78, 0xaf, 0x5f, 0x45, 0xb4, 0x2c, 0xf2, 0xc5, 0x07, 0x57, 0x7f, 0x86, 0x9e, 0xfe, 0x09, 0x00,
	0x00, 0xff, 0xff, 0x04, 0x24, 0x2d, 0x95, 0xb7, 0x04, 0x00, 0x00,
}
